package com.barberiamimi.gestioncitas.servicio;

import com.barberiamimi.gestioncitas.dto.solicitud.*;
import com.barberiamimi.gestioncitas.dto.respuesta.*;
import com.barberiamimi.gestioncitas.entidad.*;
import com.barberiamimi.gestioncitas.enumeracion.*;
import com.barberiamimi.gestioncitas.excepcion.*;
import com.barberiamimi.gestioncitas.mapper.MapperRespuestas;
import com.barberiamimi.gestioncitas.repositorio.*;
import com.barberiamimi.gestioncitas.seguridad.UsuarioAutenticado;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class ServicioAdministracion {
    private final RepositorioBarberia barberias; private final RepositorioCita citas; private final RepositorioServicio servicios; private final RepositorioProfesional profesionales;
    private final RepositorioHorarioTrabajo horarios; private final RepositorioDiaBloqueado dias; private final RepositorioDiaTrabajoEspecial trabajosEspeciales; private final RepositorioNotificacion notificaciones; private final RepositorioUsuarioAdministracion usuarios;
    private final RepositorioAuditoriaAdministrativa auditorias; private final MapperRespuestas mapper; private final ServicioDisponibilidad disponibilidad; private final PasswordEncoder codificador;
    public ServicioAdministracion(RepositorioBarberia b,RepositorioCita c,RepositorioServicio s,RepositorioProfesional p,RepositorioHorarioTrabajo h,RepositorioDiaBloqueado d,RepositorioDiaTrabajoEspecial te,RepositorioNotificacion n,RepositorioUsuarioAdministracion u,RepositorioAuditoriaAdministrativa a,MapperRespuestas m,ServicioDisponibilidad dis,PasswordEncoder co){barberias=b;citas=c;servicios=s;profesionales=p;horarios=h;dias=d;trabajosEspeciales=te;notificaciones=n;usuarios=u;auditorias=a;mapper=m;disponibilidad=dis;codificador=co;}
    @Transactional(readOnly=true) public List<CitaRespuesta> listarCitas(UsuarioAutenticado u){exigirPropietario(u);return citas.findByBarberiaIdAndProfesionalIdOrderByFechaInicioDesc(u.getBarberiaId(),u.getProfesionalId()).stream().map(mapper::cita).toList();}
    @Transactional(readOnly=true) public CitaRespuesta consultarCita(UsuarioAutenticado u,Long id){return mapper.cita(obtenerCitaAutorizada(u,id));}
    @Transactional public CitaRespuesta actualizarCita(UsuarioAutenticado u,Long id,SolicitudCrearCita s){Cita c=obtenerCitaAutorizada(u,id);exigirActiva(c);Profesional p=profesionales.findByIdAndBarberiaIdAndActivoTrue(s.profesionalId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(u.getRol()==RolUsuario.BARBERO&&!p.getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes asignar citas a otro profesional.");Servicio se=servicios.findByIdAndBarberiaIdAndActivoTrue(s.servicioId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));LocalDateTime fin=s.fechaInicio().plusMinutes(c.getBarberia().getIntervaloMinutos());disponibilidad.validarDisponibleExcluyendo(u.getBarberiaId(),p.getId(),s.fechaInicio(),fin,c.getId());c.actualizarReserva(p,se,s.nombreCliente().trim(),s.telefonoCliente().replaceAll("\\s+",""),s.fechaInicio(),fin,s.notaCliente());auditar(u,"ACTUALIZAR","CITA",c.getId());return mapper.cita(c);}
    @Transactional public CitaRespuesta cambiarEstado(UsuarioAutenticado u,Long id,SolicitudCambiarEstadoCita s){Cita c=obtenerCitaAutorizada(u,id);if(!transicionValida(c.getEstado(),s.estado()))throw new SolicitudInvalidaExcepcion("La transición de estado solicitada no está permitida.");c.setEstado(s.estado());if(s.estado()==EstadoCita.CANCELADA_POR_BARBERIA){c.setCanceladaPor(CanceladaPor.BARBERIA);c.setFechaCancelacion(LocalDateTime.now());c.setMotivoCancelacion(s.motivo());c.setCodigoCancelacionHmac(null);}auditar(u,"CAMBIAR_ESTADO","CITA",id);return mapper.cita(c);}
    @Transactional public CitaRespuesta cancelarCita(UsuarioAutenticado u,Long id,String motivo){return cambiarEstado(u,id,new SolicitudCambiarEstadoCita(EstadoCita.CANCELADA_POR_BARBERIA,motivo));}
    @Transactional(readOnly=true) public List<ServicioRespuesta> listarServicios(UsuarioAutenticado u){exigirPropietario(u);return servicios.findByBarberiaIdOrderByNombre(u.getBarberiaId()).stream().map(mapper::servicio).toList();}
    @Transactional public ServicioRespuesta crearServicio(UsuarioAutenticado u,SolicitudServicio s){exigirPropietario(u);if(servicios.existsByBarberiaIdAndNombreIgnoreCase(u.getBarberiaId(),s.nombre()))throw new RecursoDuplicadoExcepcion("Ya existe un servicio con ese nombre.");Barberia b=barberias.getReferenceById(u.getBarberiaId());Servicio creado=servicios.save(new Servicio(b,s.nombre().trim(),s.descripcion(),s.precio(),b.getIntervaloMinutos()));auditar(u,"CREAR","SERVICIO",creado.getId());return mapper.servicio(creado);}
    @Transactional public ServicioRespuesta actualizarServicio(UsuarioAutenticado u,Long id,SolicitudServicio s){exigirPropietario(u);Servicio e=servicios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));e.setNombre(s.nombre().trim());e.setDescripcion(s.descripcion());e.setPrecio(s.precio());e.setDuracionMinutos(e.getBarberia().getIntervaloMinutos());auditar(u,"ACTUALIZAR","SERVICIO",id);return mapper.servicio(e);}
    @Transactional public ServicioRespuesta estadoServicio(UsuarioAutenticado u,Long id,boolean activo){exigirPropietario(u);Servicio e=servicios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));e.setActivo(activo);auditar(u,"CAMBIAR_ESTADO","SERVICIO",id);return mapper.servicio(e);}
    @Transactional public void eliminarServicio(UsuarioAutenticado u,Long id){exigirPropietario(u);Servicio e=servicios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));if(citas.existsByBarberiaIdAndServicioId(u.getBarberiaId(),id))throw new SolicitudInvalidaExcepcion("No se puede eliminar un servicio con citas asociadas. Puedes desactivarlo para conservar el histórico.");servicios.delete(e);auditar(u,"ELIMINAR","SERVICIO",id);}
    @Transactional(readOnly=true) public List<ProfesionalAdministracionRespuesta> listarProfesionales(UsuarioAutenticado u){exigirPropietario(u);return profesionales.findByBarberiaIdOrderByNombre(u.getBarberiaId()).stream().map(this::profesionalAdministracion).toList();}
    @Transactional(readOnly=true) public List<ProfesionalRespuesta> listarEquipo(UsuarioAutenticado u){List<Profesional> equipo=u.getRol()==RolUsuario.PROPIETARIO?profesionales.findByBarberiaIdOrderByNombre(u.getBarberiaId()):profesionales.findByBarberiaIdAndActivoTrueOrderByNombre(u.getBarberiaId());return equipo.stream().map(mapper::profesional).toList();}
    @Transactional public ProfesionalAdministracionRespuesta crearProfesional(UsuarioAutenticado u,SolicitudCrearProfesional s){exigirPropietario(u);String nombreUsuario=normalizarUsuario(s.nombreUsuario());validarUsuarioDisponible(nombreUsuario,null);Barberia b=barberias.getReferenceById(u.getBarberiaId());Profesional p=profesionales.save(new Profesional(b,s.nombre().trim(),textoOpcional(s.alias())));UsuarioAdministracion acceso=usuarios.save(new UsuarioAdministracion(b,p,nombreUsuario,codificador.encode(s.contrasena()),RolUsuario.BARBERO));auditar(u,"CREAR","PROFESIONAL",p.getId());auditar(u,"CREAR","USUARIO",acceso.getId());return profesionalAdministracion(p,acceso);}
    @Transactional public ProfesionalAdministracionRespuesta actualizarProfesional(UsuarioAutenticado u,Long id,SolicitudActualizarProfesional s){exigirPropietario(u);Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));p.setNombre(s.nombre().trim());p.setAlias(textoOpcional(s.alias()));UsuarioAdministracion acceso=usuarios.findByProfesionalId(id).orElse(null);String nombreUsuario=textoOpcional(s.nombreUsuario());String contrasena=textoOpcional(s.contrasena());if(acceso==null&&(nombreUsuario==null)!=(contrasena==null))throw new SolicitudInvalidaExcepcion("Para crear el acceso debes indicar usuario y contraseña.");if(acceso==null&&nombreUsuario!=null){nombreUsuario=normalizarUsuario(nombreUsuario);validarUsuarioDisponible(nombreUsuario,null);acceso=usuarios.save(new UsuarioAdministracion(barberias.getReferenceById(u.getBarberiaId()),p,nombreUsuario,codificador.encode(contrasena),RolUsuario.BARBERO));auditar(u,"CREAR","USUARIO",acceso.getId());}else if(acceso!=null){if(nombreUsuario!=null&&!nombreUsuario.equalsIgnoreCase(acceso.getNombreUsuario())){nombreUsuario=normalizarUsuario(nombreUsuario);validarUsuarioDisponible(nombreUsuario,acceso.getId());acceso.setNombreUsuario(nombreUsuario);}if(contrasena!=null)acceso.setContrasenaHash(codificador.encode(contrasena));}auditar(u,"ACTUALIZAR","PROFESIONAL",id);return profesionalAdministracion(p,acceso);}
    @Transactional public ProfesionalAdministracionRespuesta estadoProfesional(UsuarioAutenticado u,Long id,boolean activo){exigirPropietario(u);if(Objects.equals(id,u.getProfesionalId()))throw new SolicitudInvalidaExcepcion("No puedes deshabilitar tu propio perfil profesional.");Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));p.setActivo(activo);UsuarioAdministracion acceso=usuarios.findByProfesionalId(id).orElse(null);if(acceso!=null&&acceso.getRol()==RolUsuario.BARBERO)acceso.setActivo(activo);auditar(u,"CAMBIAR_ESTADO","PROFESIONAL",id);return profesionalAdministracion(p,acceso);}
    @Transactional public void eliminarProfesional(UsuarioAutenticado u,Long id){exigirPropietario(u);if(Objects.equals(id,u.getProfesionalId()))throw new SolicitudInvalidaExcepcion("No puedes eliminar tu propio perfil profesional.");Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));UsuarioAdministracion acceso=usuarios.findByProfesionalId(id).orElse(null);if(acceso!=null&&acceso.getRol()!=RolUsuario.BARBERO)throw new SolicitudInvalidaExcepcion("No se puede eliminar el perfil profesional del propietario.");notificaciones.deleteRelacionadasConProfesional(u.getBarberiaId(),id);citas.deleteByBarberiaIdAndProfesionalId(u.getBarberiaId(),id);dias.deleteByBarberiaIdAndProfesionalId(u.getBarberiaId(),id);trabajosEspeciales.deleteByBarberiaIdAndProfesionalId(u.getBarberiaId(),id);horarios.deleteByBarberiaIdAndProfesionalId(u.getBarberiaId(),id);if(acceso!=null){auditorias.deleteByUsuarioId(acceso.getId());usuarios.delete(acceso);}profesionales.delete(p);auditar(u,"ELIMINAR","PROFESIONAL",id);}
    @Transactional(readOnly=true) public List<HorarioRespuesta> listarHorarios(UsuarioAutenticado u){return horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(u.getBarberiaId()).stream().map(mapper::horario).toList();}
    @Transactional(readOnly=true) public List<OcupacionAgendaRespuesta> listarOcupacionesEquipo(UsuarioAutenticado u){return citas.findByBarberiaIdAndEstadoInOrderByFechaInicioAsc(u.getBarberiaId(),List.of(EstadoCita.CONFIRMADA,EstadoCita.COMPLETADA)).stream().map(c->new OcupacionAgendaRespuesta(c.getProfesional().getId(),c.getProfesional().getNombre(),c.getNombreCliente(),c.getFechaInicio(),c.getFechaFin(),c.getEstado())).toList();}
    @Transactional public HorarioRespuesta crearHorario(UsuarioAutenticado u,SolicitudHorario s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarHoras(s.horaInicio(),s.horaFin());validarHorarioTrabajo(u.getBarberiaId(),p.getId(),s.diaSemana(),s.horaInicio(),s.horaFin(),null);HorarioTrabajo h=horarios.save(new HorarioTrabajo(barberias.getReferenceById(u.getBarberiaId()),p,s.diaSemana(),s.horaInicio(),s.horaFin()));auditar(u,"CREAR","HORARIO",h.getId());return mapper.horario(h);}
    @Transactional public List<HorarioRespuesta> reemplazarRutina(UsuarioAutenticado u,SolicitudRutinaSemanal s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());List<TramoRutinaSolicitud> tramos=s.tramos();for(TramoRutinaSolicitud tramo:tramos)validarHoras(tramo.horaInicio(),tramo.horaFin());for(int i=0;i<tramos.size();i++)for(int j=i+1;j<tramos.size();j++){TramoRutinaSolicitud a=tramos.get(i),b=tramos.get(j);if(a.diaSemana()==b.diaSemana()&&a.horaInicio().isBefore(b.horaFin())&&a.horaFin().isAfter(b.horaInicio()))throw new SolicitudInvalidaExcepcion("La rutina contiene tramos solapados.");}boolean cambiaConfiguracion=s.intervaloMinutos()!=null||s.diasAntelacionReserva()!=null;if(cambiaConfiguracion&&(s.intervaloMinutos()==null||s.diasAntelacionReserva()==null))throw new SolicitudInvalidaExcepcion("La configuración global debe indicar el intervalo y la antelación.");if(cambiaConfiguracion){exigirPropietario(u);Barberia b=barberias.findById(u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La barbería no existe."));b.setIntervaloMinutos(s.intervaloMinutos());b.setDiasAntelacionReserva(s.diasAntelacionReserva());}List<HorarioTrabajo> existentes=horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(u.getBarberiaId()).stream().filter(h->h.getProfesional().getId().equals(p.getId())).toList();horarios.deleteAll(existentes);horarios.flush();List<HorarioTrabajo> nuevos=tramos.stream().map(t->new HorarioTrabajo(barberias.getReferenceById(u.getBarberiaId()),p,t.diaSemana(),t.horaInicio(),t.horaFin())).toList();List<HorarioTrabajo> guardados=horarios.saveAll(nuevos);auditar(u,"REEMPLAZAR_RUTINA","PROFESIONAL",p.getId());return guardados.stream().map(mapper::horario).toList();}
    @Transactional public HorarioRespuesta actualizarHorario(UsuarioAutenticado u,Long id,SolicitudHorario s){HorarioTrabajo h=horarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El horario no existe."));obtenerProfesionalGestionable(u,h.getProfesional().getId());if(!h.getProfesional().getId().equals(s.profesionalId()))throw new SolicitudInvalidaExcepcion("No se puede cambiar el profesional de un horario.");validarHoras(s.horaInicio(),s.horaFin());validarHorarioTrabajo(u.getBarberiaId(),s.profesionalId(),s.diaSemana(),s.horaInicio(),s.horaFin(),id);h.setDiaSemana(s.diaSemana());h.setHoraInicio(s.horaInicio());h.setHoraFin(s.horaFin());auditar(u,"ACTUALIZAR","HORARIO",id);return mapper.horario(h);}
    @Transactional public void eliminarHorario(UsuarioAutenticado u,Long id){HorarioTrabajo h=horarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El horario no existe."));obtenerProfesionalGestionable(u,h.getProfesional().getId());horarios.delete(h);auditar(u,"ELIMINAR","HORARIO",id);}
    @Transactional(readOnly=true) public List<DiaBloqueadoRespuesta> listarDias(UsuarioAutenticado u){return dias.findByBarberiaIdOrderByFechaDesc(u.getBarberiaId()).stream().map(mapper::diaBloqueado).toList();}
    @Transactional public DiaBloqueadoRespuesta crearDia(UsuarioAutenticado u,SolicitudDiaBloqueado s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarFranjaOpcional(s.horaInicio(),s.horaFin());String motivo=s.motivo()==null||s.motivo().isBlank()?"Día de descanso":s.motivo().trim();DiaBloqueado d=dias.save(new DiaBloqueado(barberias.getReferenceById(u.getBarberiaId()),p,s.fecha(),s.horaInicio(),s.horaFin(),motivo));if(s.horaInicio()==null){LocalDateTime inicio=s.fecha().atStartOfDay();LocalDateTime fin=inicio.plusDays(1);List<Cita> afectadas=citas.buscarActivasEnRango(u.getBarberiaId(),p.getId(),inicio,fin);for(Cita c:afectadas){c.setEstado(EstadoCita.CANCELADA_POR_BARBERIA);c.setCanceladaPor(CanceladaPor.BARBERIA);c.setFechaCancelacion(LocalDateTime.now());c.setMotivoCancelacion("Cita cancelada al marcar el día como descanso: "+motivo);c.setCodigoCancelacionHmac(null);String fechaCita=fechaConMes(c.getFechaInicio())+" a las "+c.getFechaInicio().format(DateTimeFormatter.ofPattern("HH:mm"));notificaciones.save(new Notificacion(barberias.getReferenceById(u.getBarberiaId()),p,c,TipoNotificacion.CITA_CANCELADA,"Contactar con "+c.getNombreCliente()+" por cambio de agenda","Se canceló la cita de "+c.getNombreCliente()+" con número "+c.getTelefonoCliente()+" para el "+fechaCita+" al marcar ese día como descanso. Contacta con el cliente para avisarle."));auditar(u,"CANCELAR_POR_DESCANSO","CITA",c.getId());}}auditar(u,"CREAR","DIA_BLOQUEADO",d.getId());return mapper.diaBloqueado(d);}
    @Transactional public BloqueoParcialRespuesta crearBloqueoParcial(UsuarioAutenticado u,SolicitudBloqueoParcial s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarHoras(s.horaInicio(),s.horaFin());LocalDateTime inicio=LocalDateTime.of(s.fecha(),s.horaInicio());LocalDateTime fin=LocalDateTime.of(s.fecha(),s.horaFin());if(!inicio.isAfter(LocalDateTime.now()))throw new SolicitudInvalidaExcepcion("Solo se pueden bloquear tramos futuros.");List<DiaBloqueado> existentes=dias.findByBarberiaIdAndProfesionalIdAndFecha(u.getBarberiaId(),p.getId(),s.fecha());boolean solapado=existentes.stream().anyMatch(d->d.getHoraInicio()==null||s.horaInicio().isBefore(d.getHoraFin())&&s.horaFin().isAfter(d.getHoraInicio()));if(solapado)throw new SolicitudInvalidaExcepcion("Ese tramo ya está bloqueado total o parcialmente.");if(!estaDentroDeJornada(u.getBarberiaId(),p.getId(),s.fecha(),s.horaInicio(),s.horaFin()))throw new SolicitudInvalidaExcepcion("El tramo debe estar dentro de la jornada de trabajo.");String motivo=s.motivo()==null||s.motivo().isBlank()?"Bloqueo parcial de agenda":s.motivo().trim();DiaBloqueado bloqueo=dias.save(new DiaBloqueado(barberias.getReferenceById(u.getBarberiaId()),p,s.fecha(),s.horaInicio(),s.horaFin(),motivo));List<Cita> afectadas=citas.buscarSolapamientos(u.getBarberiaId(),p.getId(),inicio,fin);List<ContactoCitaAfectadaRespuesta> contactos=new ArrayList<>();for(Cita c:afectadas){c.setEstado(EstadoCita.CANCELADA_POR_BARBERIA);c.setCanceladaPor(CanceladaPor.BARBERIA);c.setFechaCancelacion(LocalDateTime.now());c.setMotivoCancelacion("Cita cancelada al bloquear la agenda: "+motivo);c.setCodigoCancelacionHmac(null);contactos.add(new ContactoCitaAfectadaRespuesta(c.getId(),c.getNombreCliente(),c.getTelefonoCliente(),c.getFechaInicio(),c.getFechaFin()));String fechaCita=fechaConMes(c.getFechaInicio())+" a las "+c.getFechaInicio().format(DateTimeFormatter.ofPattern("HH:mm"));notificaciones.save(new Notificacion(barberias.getReferenceById(u.getBarberiaId()),p,c,TipoNotificacion.CITA_CANCELADA,"Contactar con "+c.getNombreCliente()+" por cambio de agenda","Se canceló la cita de "+c.getNombreCliente()+" con número "+c.getTelefonoCliente()+" para el "+fechaCita+" al bloquear esa franja. Contacta con el cliente para avisarle."));auditar(u,"CANCELAR_POR_BLOQUEO","CITA",c.getId());}auditar(u,"CREAR","DIA_BLOQUEADO",bloqueo.getId());String mensaje=afectadas.isEmpty()?"Franja bloqueada. No había citas afectadas.":"Franja bloqueada y "+afectadas.size()+" cita(s) cancelada(s). Revisa Notificaciones para contactar con los clientes.";return new BloqueoParcialRespuesta(mapper.diaBloqueado(bloqueo),afectadas.size(),contactos,mensaje);}
    @Transactional public BloqueosParcialesRespuesta crearBloqueosParciales(UsuarioAutenticado u,SolicitudBloqueosParciales s){List<DiaBloqueadoRespuesta> bloqueosCreados=new ArrayList<>();Map<Long,ContactoCitaAfectadaRespuesta> contactos=new LinkedHashMap<>();for(FranjaBloqueoSolicitud tramo:s.tramos()){BloqueoParcialRespuesta resultado=crearBloqueoParcial(u,new SolicitudBloqueoParcial(s.profesionalId(),s.fecha(),tramo.horaInicio(),tramo.horaFin(),s.motivo()));bloqueosCreados.add(resultado.bloqueo());resultado.citasAfectadas().forEach(c->contactos.putIfAbsent(c.citaId(),c));}int canceladas=contactos.size();String mensaje=canceladas==0?bloqueosCreados.size()+" tramo(s) bloqueado(s). No había citas afectadas.":bloqueosCreados.size()+" tramo(s) bloqueado(s) y "+canceladas+" cita(s) cancelada(s). Revisa Notificaciones para contactar con los clientes.";return new BloqueosParcialesRespuesta(bloqueosCreados,canceladas,new ArrayList<>(contactos.values()),mensaje);}
    @Transactional public DiaBloqueadoRespuesta actualizarDia(UsuarioAutenticado u,Long id,SolicitudDiaBloqueado s){DiaBloqueado d=dias.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día bloqueado no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());if(!d.getProfesional().getId().equals(s.profesionalId()))throw new SolicitudInvalidaExcepcion("No se puede cambiar el profesional del bloqueo.");validarFranjaOpcional(s.horaInicio(),s.horaFin());d.setFecha(s.fecha());d.setHoraInicio(s.horaInicio());d.setHoraFin(s.horaFin());d.setMotivo(s.motivo());auditar(u,"ACTUALIZAR","DIA_BLOQUEADO",id);return mapper.diaBloqueado(d);}
    @Transactional public void eliminarDia(UsuarioAutenticado u,Long id){DiaBloqueado d=dias.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día bloqueado no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());dias.delete(d);auditar(u,"ELIMINAR","DIA_BLOQUEADO",id);}
    @Transactional(readOnly=true) public BarberiaRespuesta consultarConfiguracionReservas(UsuarioAutenticado u){exigirPropietario(u);return mapper.barberia(barberias.findById(u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La barbería no existe.")));}
    @Transactional public BarberiaRespuesta actualizarConfiguracionReservas(UsuarioAutenticado u,SolicitudConfiguracionReservas s){exigirPropietario(u);Barberia b=barberias.findById(u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La barbería no existe."));b.setIntervaloMinutos(s.intervaloMinutos());b.setDiasAntelacionReserva(s.diasAntelacionReserva());auditar(u,"ACTUALIZAR","CONFIGURACION_RESERVAS",b.getId());return mapper.barberia(b);}
    @Transactional(readOnly=true) public BarberiaRespuesta consultarPerfilBarberia(UsuarioAutenticado u){exigirPropietario(u);return mapper.barberia(barberias.findById(u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La barbería no existe.")));}
    @Transactional public BarberiaRespuesta actualizarPerfilBarberia(UsuarioAutenticado u,SolicitudPerfilBarberia s){exigirPropietario(u);Barberia b=barberias.findById(u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La barbería no existe."));b.setNombre(s.nombre().trim());b.setTelefono(textoOpcional(s.telefono()));b.setInstagram(textoOpcional(s.instagram()));b.setDireccion(textoOpcional(s.direccion()));b.setUrlGoogleMaps(textoOpcional(s.urlGoogleMaps()));b.setMostrarUbicacion(s.mostrarUbicacion()&&b.getDireccion()!=null);auditar(u,"ACTUALIZAR","PERFIL_BARBERIA",b.getId());return mapper.barberia(b);}
    @Transactional(readOnly=true) public List<DiaTrabajoEspecialRespuesta> listarTrabajosEspeciales(UsuarioAutenticado u){return trabajosEspeciales.findByBarberiaIdOrderByFechaAscHoraInicioAsc(u.getBarberiaId()).stream().map(mapper::diaTrabajoEspecial).toList();}
    @Transactional public DiaTrabajoEspecialRespuesta crearTrabajoEspecial(UsuarioAutenticado u,SolicitudDiaTrabajoEspecial s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarHoras(s.horaInicio(),s.horaFin());validarTrabajoEspecial(u.getBarberiaId(),p.getId(),s.fecha(),s.horaInicio(),s.horaFin(),null);DiaTrabajoEspecial creado=trabajosEspeciales.save(new DiaTrabajoEspecial(barberias.getReferenceById(u.getBarberiaId()),p,s.fecha(),s.horaInicio(),s.horaFin()));auditar(u,"CREAR","DIA_TRABAJO_ESPECIAL",creado.getId());return mapper.diaTrabajoEspecial(creado);}
    @Transactional public DiaTrabajoEspecialRespuesta actualizarTrabajoEspecial(UsuarioAutenticado u,Long id,SolicitudDiaTrabajoEspecial s){DiaTrabajoEspecial d=trabajosEspeciales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día de trabajo especial no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());if(!d.getProfesional().getId().equals(s.profesionalId()))throw new SolicitudInvalidaExcepcion("No se puede cambiar el profesional.");validarHoras(s.horaInicio(),s.horaFin());validarTrabajoEspecial(u.getBarberiaId(),s.profesionalId(),s.fecha(),s.horaInicio(),s.horaFin(),id);d.setFecha(s.fecha());d.setHoraInicio(s.horaInicio());d.setHoraFin(s.horaFin());auditar(u,"ACTUALIZAR","DIA_TRABAJO_ESPECIAL",id);return mapper.diaTrabajoEspecial(d);}
    @Transactional public void eliminarTrabajoEspecial(UsuarioAutenticado u,Long id){DiaTrabajoEspecial d=trabajosEspeciales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día de trabajo especial no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());trabajosEspeciales.delete(d);auditar(u,"ELIMINAR","DIA_TRABAJO_ESPECIAL",id);}
    @Transactional(readOnly=true) public List<NotificacionRespuesta> listarNotificaciones(UsuarioAutenticado u){exigirPropietario(u);return notificaciones.findByBarberiaIdOrderByFechaCreacionDesc(u.getBarberiaId()).stream().filter(n->n.getProfesional()==null||n.getProfesional().getId().equals(u.getProfesionalId())).map(mapper::notificacion).toList();}
    @Transactional public NotificacionRespuesta marcarLeida(UsuarioAutenticado u,Long id){exigirPropietario(u);Notificacion n=notificaciones.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La notificación no existe."));if(n.getProfesional()!=null&&!n.getProfesional().getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes consultar esa notificación.");n.marcarLeida();return mapper.notificacion(n);}
    @Transactional public UsuarioRespuesta crearUsuario(UsuarioAutenticado u,SolicitudCrearUsuario s){exigirPropietario(u);String nombreUsuario=normalizarUsuario(s.nombreUsuario());validarUsuarioDisponible(nombreUsuario,null);Profesional p=s.profesionalId()==null?null:profesionales.findByIdAndBarberiaId(s.profesionalId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(s.rol()==RolUsuario.BARBERO&&p==null)throw new SolicitudInvalidaExcepcion("Un usuario BARBERO debe estar asociado a un profesional.");if(p!=null&&usuarios.findByProfesionalId(p.getId()).isPresent())throw new RecursoDuplicadoExcepcion("Ese profesional ya tiene un usuario de acceso.");UsuarioAdministracion creado=usuarios.save(new UsuarioAdministracion(barberias.getReferenceById(u.getBarberiaId()),p,nombreUsuario,codificador.encode(s.contrasena()),s.rol()));auditar(u,"CREAR","USUARIO",creado.getId());return new UsuarioRespuesta(creado.getId(),creado.getNombreUsuario(),creado.getRol(),p==null?null:p.getId(),creado.isActivo());}
    @Transactional public MensajeRespuesta cambiarContrasena(UsuarioAutenticado u,Long id,SolicitudCambiarContrasena s){exigirPropietario(u);UsuarioAdministracion usuario=usuarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El usuario no existe."));usuario.setContrasenaHash(codificador.encode(s.nuevaContrasena()));usuario.setIntentosFallidos(0);usuario.setFechaBloqueo(null);auditar(u,"CAMBIAR_CONTRASENA","USUARIO",id);return new MensajeRespuesta("CONTRASENA_ACTUALIZADA","La contraseña se ha actualizado correctamente.");}
    private Cita obtenerCitaAutorizada(UsuarioAutenticado u,Long id){exigirPropietario(u);Cita c=citas.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La cita no existe."));if(!c.getProfesional().getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("Solo puedes acceder a tus propias citas.");return c;}
    private Profesional obtenerProfesionalGestionable(UsuarioAutenticado u,Long id){exigirPropietario(u);Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(!id.equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("Solo puedes modificar tu propia rutina laboral.");return p;}
    private void exigirPropietario(UsuarioAutenticado u){if(u.getRol()!=RolUsuario.PROPIETARIO)throw new AccesoNoAutorizadoExcepcion("La operación requiere el rol PROPIETARIO.");}
    private ProfesionalAdministracionRespuesta profesionalAdministracion(Profesional p){return profesionalAdministracion(p,usuarios.findByProfesionalId(p.getId()).orElse(null));}
    private ProfesionalAdministracionRespuesta profesionalAdministracion(Profesional p,UsuarioAdministracion acceso){return new ProfesionalAdministracionRespuesta(p.getId(),p.getNombre(),p.getAlias(),p.isActivo(),acceso==null?null:acceso.getId(),acceso==null?null:acceso.getNombreUsuario(),acceso==null?null:acceso.getRol());}
    private String normalizarUsuario(String valor){return valor.trim().toLowerCase(Locale.ROOT);}
    private void validarUsuarioDisponible(String nombreUsuario,Long usuarioActualId){usuarios.findByNombreUsuario(nombreUsuario).filter(x->!Objects.equals(x.getId(),usuarioActualId)).ifPresent(x->{throw new RecursoDuplicadoExcepcion("El nombre de usuario ya existe.");});}
    private String textoOpcional(String valor){return valor==null||valor.isBlank()?null:valor.trim();}
    private String fechaConMes(LocalDateTime fecha){String mes=fecha.format(DateTimeFormatter.ofPattern("MMMM",Locale.forLanguageTag("es-ES")));return fecha.getDayOfMonth()+" de "+mes.substring(0,1).toUpperCase(Locale.forLanguageTag("es-ES"))+mes.substring(1);}
    private void exigirActiva(Cita c){if(!c.estaActiva())throw new SolicitudInvalidaExcepcion("Solo se pueden modificar citas activas.");}
    private void validarHoras(java.time.LocalTime inicio,java.time.LocalTime fin){if(!fin.isAfter(inicio))throw new SolicitudInvalidaExcepcion("La hora final debe ser posterior a la inicial.");}
    private void validarHorarioTrabajo(Long barberiaId,Long profesionalId,java.time.DayOfWeek dia,java.time.LocalTime inicio,java.time.LocalTime fin,Long excluido){boolean solapado=horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(barberiaId,profesionalId,dia).stream().anyMatch(h->!Objects.equals(h.getId(),excluido)&&inicio.isBefore(h.getHoraFin())&&fin.isAfter(h.getHoraInicio()));if(solapado)throw new SolicitudInvalidaExcepcion("La franja de trabajo se solapa con otra existente.");}
    private void validarFranjaOpcional(java.time.LocalTime inicio,java.time.LocalTime fin){if((inicio==null)!=(fin==null))throw new SolicitudInvalidaExcepcion("La franja debe indicar ambas horas o ninguna.");if(inicio!=null)validarHoras(inicio,fin);}
    private boolean estaDentroDeJornada(Long barberiaId,Long profesionalId,java.time.LocalDate fecha,java.time.LocalTime inicio,java.time.LocalTime fin){List<DiaTrabajoEspecial> especiales=trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(barberiaId,profesionalId,fecha);if(!especiales.isEmpty())return especiales.stream().anyMatch(d->!inicio.isBefore(d.getHoraInicio())&&!fin.isAfter(d.getHoraFin()));return horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(barberiaId,profesionalId,fecha.getDayOfWeek()).stream().anyMatch(h->!inicio.isBefore(h.getHoraInicio())&&!fin.isAfter(h.getHoraFin()));}
    private void validarTrabajoEspecial(Long barberiaId,Long profesionalId,java.time.LocalDate fecha,java.time.LocalTime inicio,java.time.LocalTime fin,Long excluido){boolean bloqueado=dias.findByBarberiaIdAndProfesionalIdAndFecha(barberiaId,profesionalId,fecha).stream().anyMatch(d->d.getHoraInicio()==null);if(bloqueado)throw new SolicitudInvalidaExcepcion("El día está marcado como descanso. Elimina primero ese descanso.");boolean solapado=trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(barberiaId,profesionalId,fecha).stream().anyMatch(d->!Objects.equals(d.getId(),excluido)&&inicio.isBefore(d.getHoraFin())&&fin.isAfter(d.getHoraInicio()));if(solapado)throw new SolicitudInvalidaExcepcion("La franja especial se solapa con otra existente.");}
    private boolean transicionValida(EstadoCita origen,EstadoCita destino){if(origen==destino)return true;if(origen==EstadoCita.RESERVADA)return destino==EstadoCita.CONFIRMADA||destino==EstadoCita.CANCELADA_POR_BARBERIA;if(origen==EstadoCita.CONFIRMADA)return destino==EstadoCita.COMPLETADA||destino==EstadoCita.CANCELADA_POR_BARBERIA;return false;}
    private void auditar(UsuarioAutenticado u,String accion,String tipo,Long id){UsuarioAdministracion usuario=usuarios.getReferenceById(u.getId());auditorias.save(new AuditoriaAdministrativa(barberias.getReferenceById(u.getBarberiaId()),usuario,accion,tipo,id));}
}
