package com.barberiamimi.gestioncitas.servicio;
import com.barberiamimi.gestioncitas.entidad.*;
import com.barberiamimi.gestioncitas.excepcion.CitaNoDisponibleExcepcion;
import com.barberiamimi.gestioncitas.excepcion.SolicitudInvalidaExcepcion;
import com.barberiamimi.gestioncitas.mapper.MapperRespuestas;
import com.barberiamimi.gestioncitas.repositorio.*;
import org.junit.jupiter.api.*;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ServicioDisponibilidadPrueba {
 private final ServicioCatalogoPublico catalogo=mock(ServicioCatalogoPublico.class);private final RepositorioBarberia barberias=mock(RepositorioBarberia.class);private final RepositorioServicio servicios=mock(RepositorioServicio.class);private final RepositorioProfesional profesionales=mock(RepositorioProfesional.class);private final RepositorioHorarioTrabajo horarios=mock(RepositorioHorarioTrabajo.class);private final RepositorioDiaBloqueado bloqueos=mock(RepositorioDiaBloqueado.class);private final RepositorioDiaTrabajoEspecial trabajosEspeciales=mock(RepositorioDiaTrabajoEspecial.class);private final RepositorioCita citas=mock(RepositorioCita.class);
 private ServicioDisponibilidad servicio;private Barberia barberia;private Profesional profesional;private Servicio corte;private LocalDate fecha;
 @BeforeEach void preparar()throws Exception{reset(catalogo,barberias,servicios,profesionales,horarios,bloqueos,trabajosEspeciales,citas);barberia=new Barberia("Mimi","mimi");id(barberia,1L);profesional=new Profesional(barberia,"Mimi","mimi");id(profesional,2L);corte=new Servicio(barberia,"Corte",null,new BigDecimal("15"),30);id(corte,3L);fecha=LocalDate.now().plusDays(2);HorarioTrabajo h=new HorarioTrabajo(barberia,profesional,fecha.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(10,0));when(catalogo.buscarBarberia("mimi")).thenReturn(barberia);when(barberias.findById(1L)).thenReturn(Optional.of(barberia));when(servicios.findByIdAndBarberiaIdAndActivoTrue(3L,1L)).thenReturn(Optional.of(corte));when(profesionales.findByIdAndBarberiaIdAndActivoTrue(2L,1L)).thenReturn(Optional.of(profesional));when(horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(1L,2L,fecha.getDayOfWeek())).thenReturn(List.of(h));when(bloqueos.findByBarberiaIdAndProfesionalIdAndFecha(1L,2L,fecha)).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(1L,2L,fecha)).thenReturn(List.of());when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of());servicio=new ServicioDisponibilidad(catalogo,barberias,servicios,profesionales,horarios,bloqueos,trabajosEspeciales,citas,new MapperRespuestas());}
 @Test @DisplayName("Debe ofrecer tramos respetando la duración y el intervalo") void debeOfrecerTramos(){var r=servicio.consultar("mimi",2L,3L,fecha);assertEquals(2,r.horariosDisponibles().size());assertEquals(LocalTime.of(9,0),r.horariosDisponibles().getFirst().fechaInicio().toLocalTime());assertEquals(LocalTime.of(9,30),r.horariosDisponibles().getFirst().fechaFin().toLocalTime());}
 @Test @DisplayName("Todos los servicios deben usar el tiempo por cliente configurado") void debeUsarTiempoGlobalPorCliente()throws Exception{barberia.setIntervaloMinutos(45);Servicio rapido=new Servicio(barberia,"Corte rápido",null,new BigDecimal("20"),15);id(rapido,4L);when(servicios.findByIdAndBarberiaIdAndActivoTrue(4L,1L)).thenReturn(Optional.of(rapido));when(horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(1L,2L,fecha.getDayOfWeek())).thenReturn(List.of(new HorarioTrabajo(barberia,profesional,fecha.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(11,0))));var r=servicio.consultar("mimi",2L,4L,fecha);assertEquals(2,r.horariosDisponibles().size());assertEquals(LocalTime.of(9,0),r.horariosDisponibles().get(0).fechaInicio().toLocalTime());assertEquals(LocalTime.of(9,45),r.horariosDisponibles().get(1).fechaInicio().toLocalTime());assertEquals(LocalTime.of(10,30),r.horariosDisponibles().get(1).fechaFin().toLocalTime());}
 @Test @DisplayName("Debe rechazar por API un inicio que rompa la cadencia") void debeRechazarInicioIntermedio(){LocalDateTime inicio=LocalDateTime.of(fecha,LocalTime.of(9,15));assertThrows(CitaNoDisponibleExcepcion.class,()->servicio.validarDisponible(1L,2L,inicio,inicio.plusMinutes(30)));}
 @Test @DisplayName("Debe excluir un día completamente bloqueado") void debeExcluirDiaBloqueado(){when(bloqueos.findByBarberiaIdAndProfesionalIdAndFecha(1L,2L,fecha)).thenReturn(List.of(new DiaBloqueado(barberia,profesional,fecha,null,null,"Vacaciones")));assertTrue(servicio.consultar("mimi",2L,3L,fecha).horariosDisponibles().isEmpty());}
 @Test @DisplayName("Debe rechazar una cita fuera del horario") void debeRechazarFueraDelHorario(){LocalDateTime inicio=LocalDateTime.of(fecha,LocalTime.of(8,30));assertThrows(CitaNoDisponibleExcepcion.class,()->servicio.validarDisponible(1L,2L,inicio,inicio.plusMinutes(30)));}
 @Test @DisplayName("Debe excluir citas activas que se solapan parcialmente") void debeExcluirSolapamientos(){when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of(mock(Cita.class)));assertTrue(servicio.consultar("mimi",2L,3L,fecha).horariosDisponibles().isEmpty());}
 @Test @DisplayName("Debe validar una reprogramación ignorando la propia cita") void debeIgnorarLaPropiaCita()throws Exception{Cita propia=mock(Cita.class);when(propia.getId()).thenReturn(80L);when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of(propia));LocalDateTime inicio=LocalDateTime.of(fecha,LocalTime.of(9,0));assertDoesNotThrow(()->servicio.validarDisponibleExcluyendo(1L,2L,inicio,inicio.plusMinutes(30),80L));Cita otra=mock(Cita.class);when(otra.getId()).thenReturn(81L);when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of(otra));assertThrows(CitaNoDisponibleExcepcion.class,()->servicio.validarDisponibleExcluyendo(1L,2L,inicio,inicio.plusMinutes(30),80L));}
 @Test @DisplayName("Debe abrir un día sin rutina mediante trabajo especial") void debeAbrirDiaEspecial(){when(horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(1L,2L,fecha.getDayOfWeek())).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(1L,2L,fecha)).thenReturn(List.of(new DiaTrabajoEspecial(barberia,profesional,fecha,LocalTime.of(10,0),LocalTime.of(11,0))));var respuesta=servicio.consultar("mimi",2L,3L,fecha);assertEquals(2,respuesta.horariosDisponibles().size());assertEquals(LocalTime.of(10,0),respuesta.horariosDisponibles().getFirst().fechaInicio().toLocalTime());}
 @Test @DisplayName("Debe rechazar fechas posteriores a la antelación configurada") void debeRespetarAntelacion(){assertThrows(SolicitudInvalidaExcepcion.class,()->servicio.consultar("mimi",2L,3L,LocalDate.now().plusDays(31)));}
 @Test @DisplayName("Debe construir el calendario completo dentro de la antelación con consultas agrupadas") void debeConstruirCalendario(){HorarioTrabajo h=new HorarioTrabajo(barberia,profesional,fecha.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(10,0));when(horarios.findByBarberiaIdAndProfesionalIdAndActivoTrueOrderByDiaSemanaAscHoraInicioAsc(1L,2L)).thenReturn(List.of(h));when(bloqueos.findByBarberiaIdAndProfesionalIdAndFechaBetweenOrderByFechaAscHoraInicioAsc(eq(1L),eq(2L),any(),any())).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaBetweenOrderByFechaAscHoraInicioAsc(eq(1L),eq(2L),any(),any())).thenReturn(List.of());when(citas.buscarActivasEnRango(eq(1L),eq(2L),any(),any())).thenReturn(List.of());var respuesta=servicio.consultarCalendario("mimi",2L,3L);assertEquals(LocalDate.now(),respuesta.desde());assertEquals(LocalDate.now().plusDays(30),respuesta.hasta());assertEquals(31,respuesta.dias().size());assertTrue(respuesta.dias().stream().anyMatch(d->d.fecha().equals(fecha)&&d.disponible()));verify(citas,times(1)).buscarActivasEnRango(eq(1L),eq(2L),any(),any());}
 @Test @DisplayName("Debe mostrar fechas con solo elegir el profesional") void debeConstruirCalendarioSinServicio(){HorarioTrabajo h=new HorarioTrabajo(barberia,profesional,fecha.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(10,0));when(horarios.findByBarberiaIdAndProfesionalIdAndActivoTrueOrderByDiaSemanaAscHoraInicioAsc(1L,2L)).thenReturn(List.of(h));when(bloqueos.findByBarberiaIdAndProfesionalIdAndFechaBetweenOrderByFechaAscHoraInicioAsc(eq(1L),eq(2L),any(),any())).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaBetweenOrderByFechaAscHoraInicioAsc(eq(1L),eq(2L),any(),any())).thenReturn(List.of());when(citas.buscarActivasEnRango(eq(1L),eq(2L),any(),any())).thenReturn(List.of());var respuesta=servicio.consultarCalendario("mimi",2L,null);assertTrue(respuesta.dias().stream().anyMatch(d->d.fecha().equals(fecha)&&d.disponible()));}
 private static void id(Object o,Long valor)throws Exception{Field f=o.getClass().getDeclaredField("id");f.setAccessible(true);f.set(o,valor);}
}
