import { useEffect, useState } from 'react';
import { actualizarServicio, cambiarEstadoServicio, crearServicio, eliminarServicio, listarServicios } from '../api/serviciosApi';
import { EstadoCarga } from '../componentes/comunes/EstadoCarga';
import { EstadoVacio } from '../componentes/comunes/EstadoVacio';
import { MensajeEstado } from '../componentes/comunes/MensajeEstado';
const inicial = { nombre: '', descripcion: '', precio: '' };
export function PaginaServicios() {
  const [servicios, setServicios] = useState([]); const [formulario, setFormulario] = useState(inicial); const [editando, setEditando] = useState(null); const [cargando, setCargando] = useState(true); const [guardando, setGuardando] = useState(false); const [mensaje, setMensaje] = useState(''); const [error, setError] = useState('');
  const cargar = async () => { setCargando(true); try { setServicios(await listarServicios()); } catch (fallo) { setError(fallo.mensaje || fallo.message); } finally { setCargando(false); } };
  useEffect(() => { cargar(); }, []);
  const enviar = async (e) => { e.preventDefault(); setGuardando(true); setError(''); const datos = { ...formulario, precio: Number(formulario.precio), descripcion: formulario.descripcion || null }; try { if (editando) await actualizarServicio(editando, datos); else await crearServicio(datos); setMensaje(editando ? 'Servicio actualizado.' : 'Servicio creado.'); setFormulario(inicial); setEditando(null); await cargar(); } catch (fallo) { setError(fallo.mensaje || fallo.message); } finally { setGuardando(false); } };
  const editar = (servicio) => { setEditando(servicio.id); setFormulario({ nombre: servicio.nombre, descripcion: servicio.descripcion || '', precio: String(servicio.precio) }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const alternar = async (servicio) => { if (!window.confirm(`¿${servicio.activo ? 'Desactivar' : 'Activar'} “${servicio.nombre}”?`)) return; try { await cambiarEstadoServicio(servicio.id, !servicio.activo); setMensaje('Estado del servicio actualizado.'); await cargar(); } catch (fallo) { setError(fallo.mensaje || fallo.message); } };
  const eliminar = async (servicio) => { if (!window.confirm(`¿Eliminar definitivamente “${servicio.nombre}”? Solo será posible si no tiene citas asociadas.`)) return; setError(''); try { await eliminarServicio(servicio.id); if (editando === servicio.id) { setEditando(null); setFormulario(inicial); } setMensaje('Servicio eliminado definitivamente.'); await cargar(); } catch (fallo) { setError(fallo.mensaje || fallo.message); } };
  return <section className="contenido-panel"><div className="encabezado-pagina"><div><p className="sobrelinea">Catálogo</p><h1>Servicios</h1><p>Nombre, precio y visibilidad para las reservas.</p></div></div><MensajeEstado tipo="error">{error}</MensajeEstado><MensajeEstado tipo="exito">{mensaje}</MensajeEstado><form className="tarjeta formulario-rejilla" onSubmit={enviar}><h2>{editando ? 'Editar servicio' : 'Nuevo servicio'}</h2><label>Nombre *<input required maxLength="120" value={formulario.nombre} onChange={(e) => setFormulario({ ...formulario, nombre: e.target.value })} /></label><label>Precio (€) *<input required type="number" min="0" step="0.01" value={formulario.precio} onChange={(e) => setFormulario({ ...formulario, precio: e.target.value })} /></label><label className="campo-ancho">Descripción<textarea maxLength="600" value={formulario.descripcion} onChange={(e) => setFormulario({ ...formulario, descripcion: e.target.value })} /></label><div className="grupo-botones"><button className="boton" disabled={guardando}>{guardando ? 'Guardando…' : 'Guardar'}</button>{editando && <button type="button" className="boton boton-secundario" onClick={() => { setEditando(null); setFormulario(inicial); }}>Cancelar edición</button>}</div></form>{cargando ? <EstadoCarga /> : servicios.length === 0 ? <EstadoVacio titulo="Sin servicios" texto="Crea el primer servicio del catálogo." /> : <div className="rejilla-tarjetas">{servicios.map((servicio) => <article className={`tarjeta tarjeta-gestion ${!servicio.activo ? 'inactivo' : ''}`} key={servicio.id}><div><span className="etiqueta">{servicio.activo ? 'Activo' : 'Inactivo'}</span><h2>{servicio.nombre}</h2><p>{servicio.descripcion || 'Sin descripción'}</p></div><strong>{Number(servicio.precio).toFixed(2)} €</strong><div className="grupo-botones"><button onClick={() => editar(servicio)}>Editar</button><button onClick={() => alternar(servicio)}>{servicio.activo ? 'Desactivar' : 'Activar'}</button><button className="accion-peligro" onClick={() => eliminar(servicio)}>Eliminar</button></div></article>)}</div>}</section>;
}
